
[general]
	#A modifier to apply to the energy costs of every Thresher recipe.
	#Range: 0.0 ~ 1.7976931348623157E308
	thresher_energyModifier = 1.0
	#A modifier to apply to the time of every Thresher recipe.
	#Range: 1.0 ~ 1.7976931348623157E308
	thresher_timeModifier = 1.0
	#A modifier to apply to the energy costs of every Grist Mill recipe.
	#Range: 0.0 ~ 1.7976931348623157E308
	gristMill_energyModifier = 1.0
	#A modifier to apply to the time of every Grist Mill recipe.
	#Range: 1.0 ~ 1.7976931348623157E308
	gristMill_timeModifier = 1.0
	#A modifier to apply to the energy costs of every Power Loom recipe.
	#Range: 0.0 ~ 1.7976931348623157E308
	powerLoom_energyModifier = 1.0
	#A modifier to apply to the time of every Power Loom recipe.
	#Range: 1.0 ~ 1.7976931348623157E308
	powerLoom_timeModifier = 1.0
	#A modifier to apply to the energy costs of every Beamhouse recipe.
	#Range: 0.0 ~ 1.7976931348623157E308
	beamhouse_energyModifier = 1.0
	#A modifier to apply to the time of every Beamhouse recipe.
	#Range: 1.0 ~ 1.7976931348623157E308
	beamhouse_timeModifier = 1.0
	#The maximum amount of damage Fleshing Blades can take. While the fleshing machine is working, the blades sustain 1 damage per tick, so this is effectively the lifetime in ticks.
	#Range: > 1
	fleshingMachine_bladesDamage = 20000

[debug]
	#If true, a GUI can be opened up by rightclicking the Power Loom with a Pirn.
	enablePowerLoomDebug = false
	#If true, a GUI can be opened up by rightclicking the Fleshing Machine.
	enableFleshingMachineDebug = false

